package doobie

import cats.effect.{ExitCode, IO, IOApp}
import doobie._
import cats.implicits._
import doobie.implicits._

import java.util.UUID

object DoobieDemo extends IOApp {

  case class Actor(id: Int, name: String)

  case class Movie(id: String, title: String, year: Int, actors: List[String], director: String)

  val xa: Transactor[IO] = Transactor.fromDriverManager[IO](
    "org.postgresql.Driver",
    "jdbc:postgresql:myimdb",
    "docker",
    "docker"
  )

  def findAllActorNames: IO[List[String]] = {
    val query = sql"select name from actors".query[String]
    val action = query.to[List]
    action.transact(xa)
  }

  def findActorById(id: Int): IO[Option[Actor]] = {
    val query = sql"select id, name from actors where id = $id".query[Actor]
    val action = query.option // or statement.unique for safe way
    action.transact(xa)
  }

  val actorNamesStream: IO[List[String]] = sql"select name from actors".query[String].stream.compile.toList.transact(xa)

  // Hi level connection - HC, Hi level prepared statement - HPS
  // More low level control

  def findActorByName(name: String): IO[Option[Actor]] = {
    val queryString = "select id, name from actors where name = ?"
    HC.stream[Actor](queryString,
      HPS.set(name), // sets ?
      100
    ).compile
      .toList
      .map(_.headOption)
      .transact(xa)
  }

  // fragments - variable pieces of a statement
  def findActorsByInitial(letter: String): IO[List[Actor]] = {
    val selectPart = fr"select id, name"
    val fromPart = fr"from actors"
    val wherePart = fr"where LEFT(name, 1) = $letter"

    val statement = (selectPart ++ fromPart ++ wherePart)

    statement.query[Actor].to[List].transact(xa)
  }

  // update
  def saveActor(id: Int, name: String): IO[Int] = {
    val query = sql"insert into actors (id, name) values($id, $name)"
    query.update.run.transact(xa)
  }

  // equivalent as above
  def saveActor2(id: Int, name: String): IO[Int] = {
    val queryString = "insert into actors (id, name) values(?, ?)"

    Update[Actor](queryString).run(Actor(id, name)).transact(xa)
  }

  // auto generated ids when inserting
  def saveActorAutoGeneratedId(name: String): IO[Int] = {
    sql"insert into actors (name) values ($name)"
      .update
      .withUniqueGeneratedKeys[Int]("id")
      .transact(xa)
  }

  // update/insert man
  def saveMultipleActors(actorNames: List[String]): IO[List[Actor]] = {
    val insertStatement = "insert into actors (name) values (?)"
    val updateAction = Update[String](insertStatement).updateManyWithGeneratedKeys[Actor]("id", "name")(actorNames)
    updateAction.compile.toList.transact(xa)
  }

  // type classes
  class ActorName(val value: String) {
    override def toString: String = value
  }

  object ActorName {
    // Get & Put are fine for single types
    implicit val actorNameGet: Get[ActorName] = Get[String].map(string => new ActorName(string))
    implicit val actorNamePut: Put[ActorName] = Put[String].contramap[ActorName](actorName => actorName.value)
  }

  def findAllActorNamesCustomClass: IO[List[ActorName]] =
    sql"select name from actors".query[ActorName].to[List].transact(xa)

  // value types
  case class DirectorId(id: Int)

  case class DirectorName(name: String)

  case class DirectorLastName(lastName: String)

  case class Director(id: DirectorId, name: DirectorName, lastName: DirectorLastName)

  object Director {
    implicit val directorRead: Read[Director] = Read[(Int, String, String)].map {
      case (id, name, lastName) => Director(DirectorId(id), DirectorName(name), DirectorLastName(lastName))
    }

    implicit val directorWrite: Write[Director] = Write[(Int, String, String)].contramap[Director] {
      case Director(DirectorId(id), DirectorName(name), DirectorLastName(lastName)) => (id, name, lastName)
    }
  }

  import doobie.postgres._
  import doobie.postgres.implicits._

  // write large queries
  def findMovieByTitle(title: String): IO[Option[Movie]] = {
    val statement =
      sql"""
        select m.id, m.title, m.year_of_production, array_agg(a.name) as actors, d.name || ' ' || d.last_name
        from movies m
        join movies_actors ma ON m.id = ma.movie_id
        join actors a ON ma.actor_id = a.id
        join directors d ON m.director_id = d.id
        where m.title = $title
        group by(m.id, m.title, m.year_of_production, d.name, d.last_name)
         """

    statement.query[Movie].option.transact(xa)
  }

  def findMovieByTitle_v2(title: String): IO[Option[Movie]] = {
    def findMovieByTitle() = sql"select id, title, year_of_production, director_id from movies where title = $title"
      .query[(UUID, String, Int, Int)]
      .option

    def findDirectorByID(directorId: Int) = sql"select name, last_name from directors where id = $directorId"
      .query[(String, String)]
      .option

    def findActorsByMovieId(movieId: UUID) =
      sql"""
           select a.name
           from actors a
           join movies_actors ma ON a.id = ma.actor_id
           where ma.movie_id = $movieId
         """
        .query[String].to[List]

    val query = for {
      maybeMovie <- findMovieByTitle()
      maybeDirector <- maybeMovie match {
        case Some((_, _, _, directorId)) => findDirectorByID(directorId)
        case None => Option.empty[(String, String)].pure[ConnectionIO]
      }
      actors <- maybeMovie match {
        case Some((movieId, _, _, _)) => findActorsByMovieId(movieId)
        case None => List.empty[String].pure[ConnectionIO]
      }
    } yield for {
      (id, t, year, _) <- maybeMovie
      (name, lastName) <- maybeDirector
    } yield Movie(id.toString, t, year, actors, s"$name $lastName")

    query.transact(xa)
  }

  override def run(args: List[String]): IO[ExitCode] = findMovieByTitle_v2("Zack Snyder's Justice League").debug().as(ExitCode.Success)
}
